name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # клонируем репозиторий на виртуальную машину
    - uses: actions/checkout@v2
    
      # ставим нужный SDK (можно использовать и более старые)
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
      # генерируем статические файлы
    - name: Publish .NET Core Project
      run: dotnet publish BlazorBoard-test/BlazorBoard-test.csproj -c Release --output release
      
      # changes the base-tag in index.html from '/' to 'BlazorBoard-test' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to BlazorBoard-test
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorBoard-test\/" \/>/g' release/wwwroot/index.html
      
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: release/wwwroot
      
      
        
        
